#! /bin/bash
# depend on:
# freetype
# libxml2 (no if we install expart)
set -e
. ../env.sh
. ../toolchain.sh
dir="fontconfig-2.12.6"
cd ${ANTIX_BASE}/source
if [ ! -f "${dir}.tar.gz" ]; then
    # download it
    wget https://www.freedesktop.org/software/fontconfig/release/${dir}.tar.gz
fi
tar xvf ${dir}.tar.gz
cd ${dir}
# configure cross platform
./configure --prefix=${ANTIX_TOOLS}/${ANTIX_TARGET}\
    --build=${ANTIX_HOST} \
    --host=${ANTIX_TARGET}\
    --disable-docs \
    --with-arch=${ANTIX_ARCH}
# -arch ${ANTIX_ARCH}
# --enable-libxml2\
make -j8
make install
#cp -avrf ${ANTIX_PKG_BUILD}/freetype/usr/local/* ${ANTIX_TOOLS}/${ANTIX_TARGET}/
cp -avrf ${ANTIX_TOOLS}/${ANTIX_TARGET}/bin/fc-* ${ANTIX_ROOT}/usr/bin
cp -avrf ${ANTIX_TOOLS}/${ANTIX_TARGET}/lib/libfontconfig.so* ${ANTIX_ROOT}/usr/lib
mkdir -p ${ANTIX_ROOT}/etc/fonts/conf.d
cat > ${ANTIX_ROOT}/etc/fonts/fonts.conf << "EOF"
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<!-- /etc/fonts/fonts.conf file to configure system font access -->
<fontconfig>

<!--
	DO NOT EDIT THIS FILE.
	IT WILL BE REPLACED WHEN FONTCONFIG IS UPDATED.
	LOCAL CHANGES BELONG IN 'local.conf'.

	The intent of this standard configuration file is to be adequate for
	most environments.  If you have a reasonably normal environment and
	have found problems with this configuration, they are probably
	things that others will also want fixed.  Please submit any
	problems to the fontconfig bugzilla system located at fontconfig.org

	Note that the normal 'make install' procedure for fontconfig is to
	replace any existing fonts.conf file with the new version.  Place
	any local customizations in local.conf which this file references.

	Keith Packard
-->

<!-- Font directory list -->

	<dir>/usr/share/fonts</dir>
	
	<dir prefix="xdg">fonts</dir>
	<!-- the following element will be removed in the future -->
	<dir>~/.fonts</dir>

<!--
  Accept deprecated 'mono' alias, replacing it with 'monospace'
-->
	<match target="pattern">
		<test qual="any" name="family">
			<string>mono</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>monospace</string>
		</edit>
	</match>

<!--
  Accept alternate 'sans serif' spelling, replacing it with 'sans-serif'
-->
	<match target="pattern">
		<test qual="any" name="family">
			<string>sans serif</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>sans-serif</string>
		</edit>
	</match>

<!--
  Accept deprecated 'sans' alias, replacing it with 'sans-serif'
-->
	<match target="pattern">
		<test qual="any" name="family">
			<string>sans</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>sans-serif</string>
		</edit>
	</match>

<!--
  Load local system customization file
-->
	<include ignore_missing="yes">conf.d</include>

<!-- Font cache directory list -->

	<cachedir>/var/cache/fontconfig</cachedir>
	<cachedir prefix="xdg">fontconfig</cachedir>
	<!-- the following element will be removed in the future -->
	<cachedir>~/.fontconfig</cachedir>

	<config>
<!--
  Rescan configuration every 30 seconds when FcFontSetList is called
 -->
		<rescan>
			<int>30</int>
		</rescan>
	</config>

</fontconfig>
EOF
mkdir -p ${ANTIX_ROOT}/var/cache/fontconfig
#cp -avrf ${ANTIX_PKG_BUILD}/freetype/usr/local/bin/freetype-config ${ANTIX_ROOT}/usr/bin
cd ${ANTIX_BASE}/source
rm -rf ${dir}